/**
 * Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
 * 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 * By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms
 */
public class evenFibNums {
    public static void main(String[] args) {
        int answer = 2;
        int prevNum = 1;

        while (answer < 4) {
            int nextPrevNum = answer;
            answer += prevNum;
            prevNum = nextPrevNum;
        }

        System.out.println("Answer  = " + answer);
    }
}
